name: Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        name: Build and Test (${{ matrix.os }})
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup Zig
            uses: mlugg/setup-zig@v2
            with:
                version: '0.16.0'
          - name: Setup Vulkan SDK
            uses: humbletim/setup-vulkan-sdk@v1.2.1
            with:
                vulkan-query-version: 1.4.304.1
                vulkan-components: Vulkan-Headers, Vulkan-Loader
                vulkan-use-cache: true
          - name: Install Dependencies (Ubuntu)
            if: matrix.os == 'ubuntu-latest'
            run: |
              sudo apt-get update
              sudo apt-get install -y libgl1-mesa-dev xorg-dev
          - name: Build
            run: cd examples && zig build